n = int(input('Введите число: '))
gen_one = (num for num in range(1, n+1, 2))
print(gen_one)
print(type(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))
print(next(gen_one))